version = 0.1

[default.deploy.parameters]
stack_name = "HealthcareDataQualityStackV6"
resolve_s3 = true
s3_prefix = "HealthcareDataQualityStackV6"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "RawDataBucketName=\"\" CuratedDataBucketName=\"\" QuarantineDataBucketName=\"\" BedrockRegion=\"us-east-1\" BedrockModelId=\"anthropic.claude-3-haiku-20240307-v1:0\""
image_repositories = []
